### ISSUE TITLE
NPM issue

### ISSUE THREAD

**Issue by Sasytoremember** [MacaylaMarvelous81/sm64js-mod#4]

**Comment by Sasytoremember** [comment]
$ npm ERR! code ENOENT
npm ERR! path C:\Users\Brandon\Downloads\sm64js-mod-master\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Brandon\Downloads\sm64js-mod-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by MacaylaMarvelous81** [comment]
Can you run this command and tell me output?
dir
(in the same directory)
